# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LJuM2mc7KGqncL6NudnfvFC9j2-TwyYx
"""

import matplotlib.pyplot as plt
import pandas as ps

df=ps.read_csv('student.csv')
df

plt.pie(df.iloc[:,1],labels=df.iloc[:,0],explode=(0.3,0,0,0.9,0))

plt.show()

