# -*- coding: utf-8 -*-
"""diabetest

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sgo5nSWZmjSEVIT1pkeV4zAidbfUpmaX
"""

import pandas as pd

df=pd.read_csv("http://13.234.66.67/summer19/datasets/diabetest.csv")

df.info()

df.describe()

#top 5 column
df.head(5)

import seaborn as sb

#plot particular column with count
sb.countplot(df['Pregnancies'])

df.hist(figsize=(15,20))                           # this is -----hist flot

sb.scatterplot(df['Pregnancies'],df['Glucose'])

sb.pairplot(df)

#extract attribute from dataframe
features=df.iloc[:,0:8].values

features

